name: Storm CMS
description: A base profile for Drupal 10 with rich features for faster development and head start.
recipes:
  - storm_cms_core
  - storm_cms_editor
  - storm_cms_user
  - storm_cms_webform
  - storm_cms_page
  - storm_cms_person
  - storm_cms_article
